# 网址
baseURL = 'https://example.org/'

# 默认语言
defaultContentLanguage = "zh-cn"

# 网站语言
languageCode = "zh-CN"

# 包含中日韩语言
hasCJKLanguage = true

# 网站站标题
title = "诶嘿？"

# 使用的主题
theme = "DoIt"

enableEmoji = true

[params]
    # DoIt 使用的主题版本
    version = "0.4.X"

    description = "诶嘿"

    # 网站默认主题样式
    defaultTheme = "auto"

    # dateFormat = "2024-10-24"

    enablePWA = false
    
    [params.footer]
        enable = true
        hugo = true
        copyright = true
        author = true
        since = 2024

    [params.section]
        paginate = 50

    [params.list]
        paginate = 50

    [params.page.toc]
        enable = true
        keepStatic = false
        auto = true

    [params.page.code]
        copy = true
        maxShownLines = 50

[author]
    name = "青梓朝梧"
    email = "fonstie@gmail.com"

[languages]
    [languages.zh-cn]
        weight = 1
        languageCode = "zh-CN"
        languageName = "简体中文"
        hasCJKLanguage = true
        [languages.zh-cn.params.home.profile]
            enable = true
            avatarURL = "/avatar/avatar1.jpg"
            title = ""
            subtitle = "这里啥都没有哦"
            typeit = true
            social = true
            disclaimer = ""
        [languages.zh-cn.params.home.posts]
            enable = true
            paginate = 10
    
        [[languages.zh-cn.menu.main]]
            identifier = "series"
            pre = ""
            post = ""
            name = "系列"
            url = "/series/"
            title = ""
            weight = 3
        [[languages.zh-cn.menu.main]]
            identifier = "tech"
            pre = ""
            post = ""
            name = "技术"
            url = "/categories/tech/"
            title = ""
            weight = 5
        [[languages.zh-cn.menu.main]]
            identifier = "life"
            pre = ""
            post = ""
            name = "生活"
            url = "/categories/life/"
            title = ""
            weight = 7
        [[languages.zh-cn.menu.main]]
            identifier = "diary"
            pre = ""
            post = ""
            name = "日记"
            url = "/categories/diary/"
            title = ""
            weight = 9
        [[languages.zh-cn.menu.main]]
            identifier = "tags"
            pre = ""
            post = ""
            name = "标签"
            url = "/tags/"
            title = ""
            weight = 11
        [[languages.zh-cn.menu.main]]
            identifier = "now"
            pre = ""
            post = ""
            name = "此刻"
            url = "/now/"
            title = ""
            weight = 13
        [[languages.zh-cn.menu.main]]
            identifier = "friends"
            pre = ""
            post = ""
            name = "朋友们"
            url = "/friends/"
            title = ""
            weight = 15
        [[languages.zh-cn.menu.main]]
            identifier = "about"
            pre = ""
            post = ""
            name = "关于"
            url = "/about/"
            title = ""
            weight = 17

    [languages.en]
        weight = 2
        languageCode = "en"
        languageName = "English"
        [languages.en.params.home.profile]
            enable = true
            avatarURL = "/avatar/avatar1.jpg"
            title = ""
            subtitle = "???"
            typeit = false
            social = true
        [languages.en.params.home.posts]
            enable = true
            paginate = 10
    
        [[languages.en.menu.main]]
            identifier = "series"
            pre = ""
            post = ""
            name = "系列"
            url = "/series/"
            title = ""
            weight = 3
        [[languages.en.menu.main]]
            identifier = "tech"
            pre = ""
            post = ""
            name = "技术"
            url = "/categories/tech/"
            title = ""
            weight = 5
        [[languages.en.menu.main]]
            identifier = "life"
            pre = ""
            post = ""
            name = "生活"
            url = "/categories/life/"
            title = ""
            weight = 7
        [[languages.en.menu.main]]
            identifier = "tags"
            pre = ""
            post = ""
            name = "标签"
            url = "/tags/"
            title = ""
            weight = 9
        [[languages.en.menu.main]]
            identifier = "now"
            pre = ""
            post = ""
            name = "此刻"
            url = "/now/"
            title = ""
            weight = 11
        [[languages.zh-cn.menu.main]]
            identifier = "friends"
            pre = ""
            post = ""
            name = "朋友们"
            url = "/friends/"
            title = ""
            weight = 15
        [[languages.zh-cn.menu.main]]
            identifier = "about"
            pre = ""
            post = ""
            name = "关于"
            url = "/about/"
            title = ""
            weight = 17

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        noClasses = false

    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions.cjk]
            enable = true
            eastAsianLineBreaks = true
            escapeSpace = true
    
    # 目录设置
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[Permalinks]
    posts = "posts/:filename"

[taxonomies]
    author = "author"
    category = "categories"
    tag = "tags"
    series = "series"

[outputs]
    home = ["HTML", "ATOM", "JSON", "RSS"]
    page = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomy = ["HTML"]
