baseURL = 'https://example.org/'
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
title = "诶嘿？"

theme = "DoIt"

[params]
    version = "0.4.X"

[markup]
    [markup.highlight]
        noClasses = false
